"""updated role model

Revision ID: cd032af7b16e
Revises: ba89214bc8e5
Create Date: 2025-04-17 15:44:56.848626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd032af7b16e'
down_revision: Union[str, None] = 'ba89214bc8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_unique_constraint(None, 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'display_name')
    # ### end Alembic commands ###
